=== andres0sorio/GRBsWork/NeutrinoPhysics/nueosci01/bin/matrix_config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT MixingParameterList (MixingParameters)+ >
<!ELEMENT MixingParameters (Par1,Par2,Par3,Par4,Par5,Par6,Par7) >
<!ATTLIST MixingParameters
  Id	CDATA	#REQUIRED
>

<!ELEMENT Par1 (#PCDATA) >
<!ELEMENT Par2 (#PCDATA) >
<!ELEMENT Par3 (#PCDATA) >
<!ELEMENT Par4 (#PCDATA) >
<!ELEMENT Par5 (#PCDATA) >
<!ELEMENT Par6 (#PCDATA) >
<!ELEMENT Par7 (#PCDATA)> 

<!ATTLIST Par1
  Name	CDATA	#REQUIRED
>

<!ATTLIST Par2
  Name	CDATA	#REQUIRED
>

<!ATTLIST Par3
  Name	CDATA	#REQUIRED
>

<!ATTLIST Par4
  Name	CDATA	#REQUIRED
>

<!ATTLIST Par5
  Name	CDATA	#REQUIRED
>

<!ATTLIST Par6
  Name	CDATA	#REQUIRED
>

<!ATTLIST Par7
  Name	CDATA	#REQUIRED
>

=== andres0sorio/GRBsWork/NeutrinoPhysics/nueosci01/bin/matrix_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE MixingParameterList PUBLIC "" "matrix_config.dtd" []>
<MixingParameterList>
  <MixingParameters Id="1">
    <Par1 Name="theta_12">
      33.83
    </Par1>
    <Par2 Name="theta_13">
      11.39
    </Par2>
    <Par3 Name="theta_23">
      45.0
    </Par3>
    <Par4 Name="Dm23sq">
      0.0024
    </Par4>
    <Par5 Name="L[m]">
      1.0e5
    </Par5>
    <Par6 Name="Enu">
      5.0e6
    </Par6>
    <Par7 Name="Ve">
      5.32e-13
    </Par7>
    <Par8 Name="Dm21sq">
      0.00008
    </Par8>
    <Par9 Name="dCP">
      180.0
    </Par9>
  </MixingParameters>
</MixingParameterList>
