=== andres0sorio/GRBsWork/NeutrinoPhysics/nueosci01/bin/model_config.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT ModelParameterList (ModelParameters)+ >
<!ELEMENT ModelParameters (Par)+ >
<!ELEMENT Par (#PCDATA) >

<!ATTLIST ModelParameters
  Id	CDATA	#REQUIRED
>

<!ATTLIST Par
  Id	CDATA	#REQUIRED
  Name  CDATA	#REQUIRED
>

=== andres0sorio/GRBsWork/NeutrinoPhysics/nueosci01/bin/model_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ModelParameterList PUBLIC "" "model_config.dtd" []>
<ModelParameterList>
  <ModelParameters Id="ModelA">
    <Par Id="0" Name="MaxPars">
      2.0
    </Par>
    <Par Id="1" Name="K0">
      1.51052e-19
    </Par>
    <Par Id="2" Name="LMAX">
      1.5228e+17
    </Par>
    <Par Id="3" Name="LMIN">
      4.0608e+15
    </Par>
    <Par Id="4" Name="Emin">
      1.0e11
    </Par>
    <Par Id="5" Name="Emax">
      1.0e14
    </Par>
    <Par Id="6" Name="Dx">
      0.5e14
    </Par>
    <Par Id="7" Name="De">
      1.0e10
    </Par>
  </ModelParameters>
  <ModelParameters Id="ModelB">
    <Par Id="0" Name="MaxPars">
      4.0
    </Par>
    <Par Id="1" Name="KB">
      1.28e-018
    </Par>
    <Par Id="2" Name="LMAX">
      1.5228e+17
    </Par>
    <Par Id="3" Name="rB">
      5.076e+016
    </Par>
    <Par Id="4" Name="cm2InvEvFactor">
      5.076e+8
    </Par>
    <Par Id="5" Name="LMIN">
      4.0608e+15
    </Par>
    <Par Id="6" Name="Emin">
      1.0E11
    </Par>
    <Par Id="7" Name="Emax">
      1.0E14
    </Par>
    <Par Id="8" Name="Dx">
      0.5E14
    </Par>
    <Par Id="9" Name="De">
      1.0E9
    </Par>
  </ModelParameters>
  <ModelParameters Id="ModelC">
    <Par Id="0" Name="MaxPars">
      3.0
    </Par>
    <Par Id="1" Name="KC">
      2.38e-019
    </Par>
    <Par Id="2" Name="LMAX">
      1.5228e+17
    </Par>
    <Par Id="3" Name="cm2InvEvFactor">
      5.076e+8
    </Par>
    <Par Id="4" Name="LMIN">
      4.0608e+15
    </Par>
    <Par Id="5" Name="Emin">
      1.0e11
    </Par>
    <Par Id="6" Name="Emax">
      1.0e14
    </Par>
    <Par Id="7" Name="Dx">
      0.5e14
    </Par>
    <Par Id="8" Name="De">
      1.0e9
    </Par>
  </ModelParameters>
  <ModelParameters Id="EarthA">
    <Par Id="0" Name="MaxPars">
      5.0
    </Par>
    <Par Id="1" Name="H1">
      1.7E-13
    </Par>
    <Par Id="2" Name="H2">
      4.4E-13
    </Par>
    <Par Id="3" Name="S1">
      2.885e6
    </Par>
    <Par Id="4" Name="S2">
      6.972e6
    </Par>
    <Par Id="5" Name="m2InvEvFactor">
      5.076e+6
    </Par>
    <Par Id="6" Name="LMIN">
      0.0
    </Par>
    <Par Id="7" Name="LMAX">
      7.0780e13
    </Par>
    <Par Id="8" Name="Emin">
      1.0e9
    </Par>
    <Par Id="9" Name="Emax">
      1.0e10
    </Par>
    <Par Id="10" Name="Dx">
      1.0e12
    </Par>
    <Par Id="11" Name="De">
      1.0e8
    </Par>
  </ModelParameters>
 </ModelParameterList>

=== andres0sorio/GRBsWork/NeutrinoPhysics/nueosci01/bin/model_config_validation.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ModelParameterList PUBLIC "" "model_config.dtd" []>
<ModelParameterList>
<ModelParameters Id="LinearFig1">
    <Par Id="0" Name="MaxPars">
      0.0
    </Par>
    <Par Id="1" Name="LMIN">
      1.0e-14
    </Par>
    <Par Id="2" Name="LMAX">
      1.0e-13
    </Par>
    <Par Id="3" Name="Dx">
      0.02e-13
    </Par>
    <Par Id="4" Name="Ev">
      10.0e9
    </Par>
  </ModelParameters>
  <ModelParameters Id="LinearFig3">
    <Par Id="0" Name="MaxPars">
      0.0
    </Par>
    <Par Id="1" Name="LMIN">
      1.0e-22
    </Par>
    <Par Id="2" Name="LMAX">
      1.0e-12
    </Par>
    <Par Id="3" Name="Dx">
      1.0e-23
    </Par>
    <Par Id="4" Name="Ev">
      10.0e9
    </Par>
  </ModelParameters>
  <ModelParameters Id="Linear1TeV">
    <Par Id="0" Name="MaxPars">
      0.0
    </Par>
    <Par Id="1" Name="LMIN">
      1.0e-22
    </Par>
    <Par Id="2" Name="LMAX">
      1.0e-12
    </Par>
    <Par Id="3" Name="Dx">
      1.0e-23
    </Par>
    <Par Id="4" Name="Ev">
      1.0e12
    </Par>
  </ModelParameters>
 <ModelParameters Id="Linear10TeV">
    <Par Id="0" Name="MaxPars">
      0.0
    </Par>
    <Par Id="1" Name="LMIN">
      1.0e-22
    </Par>
    <Par Id="2" Name="LMAX">
      1.0e-12
    </Par>
    <Par Id="3" Name="Dx">
      1.0e-23
    </Par>
    <Par Id="4" Name="Ev">
      1.0e13
    </Par>
  </ModelParameters>
</ModelParameterList>

=== andres0sorio/GRBsWork/NeutrinoPhysics/nueosci01/bin/model_config_Earth.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ModelParameterList PUBLIC "" "model_config.dtd" []>
<ModelParameterList>
  <ModelParameters Id="EarthA">
    <Par Id="0" Name="MaxPars">
      5.0
    </Par>
    <Par Id="1" Name="H1">
      3.40e-13
    </Par>
    <Par Id="2" Name="H2">
      8.69e-13
    </Par>
    <Par Id="3" Name="L1.m">
      2.885e6
    </Par>
    <Par Id="4" Name="L2.m">
      8.17e6
    </Par>
    <Par Id="5" Name="M.to.invEV">
      5.076e+6
    </Par>
    <Par Id="6" Name="LMIN">
      0.0
    </Par>
    <Par Id="7" Name="LMAX">
      7.0780e13
    </Par>
    <Par Id="8" Name="Emin">
      1.0e9
    </Par>
    <Par Id="9" Name="Emax">
      1.0e10
    </Par>
    <Par Id="10" Name="Dx">
      1.0e10
    </Par>
    <Par Id="11" Name="De">
      1.0e8
    </Par>
  </ModelParameters>
  <ModelParameters Id="EarthB">
    <Par Id="0" Name="MaxPars">
      3.0
    </Par>
    <Par Id="1" Name="Diameter">
      7.0780e13
    </Par>
    <Par Id="2" Name="cFact1">
      4.2951e+18
    </Par>
    <Par Id="3" Name="cFact2">
      1.76e-32
    </Par>
    <Par Id="4" Name="LMIN">
      0.0
    </Par>
    <Par Id="5" Name="LMAX">
      7.0780e13
    </Par>
    <Par Id="6" Name="Emin">
      1.0e9
    </Par>
    <Par Id="7" Name="Emax">
      1.0e10
    </Par>
    <Par Id="8" Name="Dx">
      1.0e10
    </Par>
    <Par Id="9" Name="De">
      1.0e8
    </Par>
  </ModelParameters>
  <ModelParameters Id="ZeroPt">
    <Par Id="0" Name="MaxPars">
      0.0
    </Par>
    <Par Id="2" Name="LMAX">
      1.61e+17
    </Par>
    <Par Id="3" Name="LMIN">
      3.20e+15
    </Par>
    <Par Id="4" Name="Emin">
      1.0e11
    </Par>
    <Par Id="5" Name="Emax">
      1.0e14
    </Par>
    <Par Id="6" Name="Dx">
      0.5e14
    </Par>
    <Par Id="7" Name="De">
      1.0e9
    </Par>
  </ModelParameters>
 </ModelParameterList>

=== andres0sorio/GRBsWork/NeutrinoPhysics/nueosci01/bin/model_config_SetI.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ModelParameterList PUBLIC "" "model_config.dtd" []>
<ModelParameterList>
  <ModelParameters Id="ModelA">
    <Par Id="0" Name="MaxPars">
      2.0
    </Par>
    <Par Id="1" Name="K0">
      3.02e-19
    </Par>
    <Par Id="2" Name="LMAX">
      1.5736E+017
    </Par>
    <Par Id="3" Name="LMIN">
      3.2027E+015
    </Par>
    <Par Id="4" Name="Emin">
      1.0e11
    </Par>
    <Par Id="5" Name="Emax">
      1.0e14
    </Par>
    <Par Id="6" Name="Dx">
      0.5e14
    </Par>
    <Par Id="7" Name="De">
      1.0e9
    </Par>
  </ModelParameters>
  <ModelParameters Id="EarthB">
    <Par Id="0" Name="MaxPars">
      3.0
    </Par>
    <Par Id="1" Name="Diameter">
      7.0780e13
    </Par>
    <Par Id="2" Name="cFact1">
      4.2951e+18
    </Par>
    <Par Id="3" Name="cFact2">
      1.76e-32
    </Par>
    <Par Id="4" Name="LMIN">
      0.0
    </Par>
    <Par Id="5" Name="LMAX">
      7.0780e13
    </Par>
    <Par Id="6" Name="Emin">
      1.0e9
    </Par>
    <Par Id="7" Name="Emax">
      1.0e10
    </Par>
    <Par Id="8" Name="Dx">
      1.0e10
    </Par>
    <Par Id="9" Name="De">
      0.1e8
    </Par>
  </ModelParameters>
 </ModelParameterList>

=== andres0sorio/GRBsWork/NeutrinoPhysics/nueosci02/bin/model_config_Earth.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ModelParameterList PUBLIC "" "model_config.dtd" []>
<ModelParameterList>
  <ModelParameters Id="EarthB">
    <Par Id="0" Name="MaxPars">
      3.0
    </Par>
    <Par Id="1" Name="Diameter">
      6.4750e+13
    </Par>
    <Par Id="2" Name="cFact1">
      4.2951e+18
    </Par>
    <Par Id="3" Name="cFact2">
      1.76e-32
    </Par>
    <Par Id="4" Name="LMIN">
      0.0
    </Par>
    <Par Id="5" Name="LMAX">
      6.4750e+13
    </Par>
    <Par Id="6" Name="Emin">
      1.0e11
    </Par>
    <Par Id="7" Name="Emax">
      1.0e17
    </Par>
    <Par Id="8" Name="Dx">
      1.0e10
    </Par>
    <Par Id="9" Name="De">
      1.0e10
    </Par>
  </ModelParameters>
  <ModelParameters Id="ZeroPt">
    <Par Id="0" Name="MaxPars">
      0.0
    </Par>
    <Par Id="2" Name="LMAX">
      1.61e+17
    </Par>
    <Par Id="3" Name="LMIN">
      3.20e+15
    </Par>
    <Par Id="4" Name="Emin">
      1.0e11
    </Par>
    <Par Id="5" Name="Emax">
      1.0e14
    </Par>
    <Par Id="6" Name="Dx">
      0.5e14
    </Par>
    <Par Id="7" Name="De">
      1.0e9
    </Par>
  </ModelParameters>
 </ModelParameterList>
